### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by TonKro** [lmatula/ha_chint_pm#38]
I connected the DTSU666 with a RS485 serial port on my pi. When add a integration I choose the serial port. But whatever I try I keep getting the message UNKOWN error.

![Image](https://github.com/user-attachments/assets/db7e5f4a-581a-484c-bdc7-e7f0de4953f7)

Can anyone help me?

**Comment by scruysberghs** [comment]
can't help, but am seeing the same thing. Probably the modbus library changes in the home assistant versions since 202502 

![Image](https://github.com/user-attachments/assets/1b0b3fe9-efa7-4580-9001-e83e708bfce9)

**Comment by TonKro** [comment]
Are there maybe other solutions to make it visible in home assistant? Or
maybe by node-red or iobroker?

Op vr 4 apr 2025 om 08:48 schreef Steven Cruysberghs <
***@***.***>:

**Comment by scruysberghs** [comment]
I have used chatgpt to quickly generate a [home assistant package](https://www.home-assistant.io/docs/configuration/packages/) yaml file starting from the pdf documentation with all the modbus registers that is in the docs folder of this repo.

````
modbus:
  - name: dtsu666
    type: serial
    method: rtu
    port: /dev/ttyUSB0
    baudrate: 9600
    stopbits: 1
    bytesize: 8
    parity: N
    timeout: 1
    delay: 1
    message_wait_milliseconds: 100

    sensors:
      - name: "DTSU666 Voltage L1"
        slave: 11
        address: 0x2006
        input_type: holding
        data_type: float32
        scale: 0.1
        precision: 1
        unit_of_measurement: "V"

      - name: "DTSU666 Current L1"
        slave: 11
        address: 0x200C
        input_type: holding
        data_type: float32
        scale: 0.001
        precision: 3
        unit_of_measurement: "A"

      - name: "DTSU666 Active Power Total"
        slave: 11
        address: 0x2012
        input_type: holding
        data_type: float32
        precision: 0
        unit_of_measurement: "W"

      - name: "DTSU666 Reactive Power Total"
        slave: 11
        address: 0x201A
        input_type: holding
        data_type: float32
        precision: 0
        unit_of_measurement: "var"

      - name: "DTSU666 Power Factor"
        slave: 11
        address: 0x202A
        input_type: holding
        data_type: float32
        scale: 0.001
        precision: 3

      - name: "DTSU666 Frequency"
        slave: 11
        address: 0x2044
        input_type: holding
        data_type: float32
        scale: 0.01
        precision: 2
        unit_of_measurement: "Hz"

      - name: "DTSU666 Import Energy"
        slave: 11
        address: 0x401E
        input_type: holding
        data_type: float32
        precision: 1
        unit_of_measurement: "kWh"

      - name: "DTSU666 Export Energy"
        slave: 11
        address: 0x4028
        input_type: holding
        data_type: float32
        precision: 1
        unit_of_measurement: "kWh"
```
output is this:


![Image](https://github.com/user-attachments/assets/223e22d8-dfd8-4fb6-85ad-59779afa759c)

![Image](https://github.com/user-attachments/assets/56e46a54-b3f8-4361-9b6c-0abd52166c55)
